### PR TITLE
Angela

### PR DESCRIPTION
**Pull request by Angela-sq**

### CODE REVIEW

**Comment by Angela-sq** [comment]
I forgot what I changed in the Berkeley, Stanford, Wellesley notebooks. It'll probably be best to keep what you had before on master

**Comment by theodoremui** [comment]
per your comment, we are going to close this PR.

**Comment by Angela-sq** [comment]
I tried resolving conflicts by deleting the notebooks with conflicts on my branch and then pushing and opening the pr again. I don't think it worked lol
Can you try resolving conflicts on your end and just taking the version on master? I don't think I'm authorized to do so

**Review by theodoremui — COMMENTED** [review]
looks good

**Review by theodoremui — APPROVED** [review]
approving this request

**Pull request merged**
